package f1mini;


import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anush
 */
public class f1 extends javax.swing.JFrame {
     Connection con;
     Statement stmt;
     PreparedStatement pstmt;
     ResultSet rs;
     CallableStatement cstmt;
    /**
     * Creates new form f1
     */
    public f1() {
        try
      {
          Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          JOptionPane.showMessageDialog(this,"Driver Loaded");
          try
          {
              con=DriverManager.getConnection("jdbc:odbc:gotham","gouthammv","mypass");
              JOptionPane.showMessageDialog(this,"connection established");
          }
          catch(SQLException ex)
          {
              JOptionPane.showMessageDialog(this,ex.getMessage());
          }
      }
      catch(ClassNotFoundException ex){
          JOptionPane.showMessageDialog(this, ex.getMessage());
      }
   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statisticspane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        driver_no = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        gpwins = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insertbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        team_no = new javax.swing.JTextField();
        team = new javax.swing.JTextField();
        engine = new javax.swing.JTextField();
        base_op = new javax.swing.JTextField();
        driver1 = new javax.swing.JTextField();
        driver2 = new javax.swing.JTextField();
        principal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        teams_insert = new javax.swing.JButton();
        teams_update = new javax.swing.JButton();
        teams_delete = new javax.swing.JButton();
        teams_display = new javax.swing.JButton();
        teams_clear = new javax.swing.JButton();
        teams_exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        raceid = new javax.swing.JTextField();
        gpname = new javax.swing.JTextField();
        circuit = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        date_of_race = new javax.swing.JTextField();
        no_of_laps = new javax.swing.JTextField();
        lap_length = new javax.swing.JTextField();
        winning_driver = new javax.swing.JTextField();
        winning_team = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        gps_ins = new javax.swing.JButton();
        gps_upd = new javax.swing.JButton();
        gps_del = new javax.swing.JButton();
        gps_disp = new javax.swing.JButton();
        gps_clear = new javax.swing.JButton();
        gps_exit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drivstandings = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamstandings = new javax.swing.JTextArea();
        drivchampbutton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        drivchamp = new javax.swing.JTextArea();
        teamchampbutton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        teamchamp = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        gpnamestat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        gpdatestat = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        gpwinningdriver = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        gpwinningteam = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        drivraceswon = new javax.swing.JTextArea();
        drivname = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        findracedrivwon = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        statfinddetails = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        stateamname = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        statraceswonteam = new javax.swing.JTextArea();
        teamraceswon = new javax.swing.JButton();
        clearstat = new javax.swing.JButton();
        exitstat = new javax.swing.JButton();
        standingsdisp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Driver No");

        jLabel2.setText("Name");

        jLabel3.setText("Nationality");

        jLabel4.setText("GP Wins");

        insertbutton.setText("Insert");

        updatebutton.setText("Update");

        deletebutton.setText("Delete");

        displaybutton.setText("Display");

        clearbutton.setText("Clear");

        exitbutton.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insertbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displaybutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(driver_no)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(nationality)
                            .addComponent(gpwins))))
                .addContainerGap(724, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(driver_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpwins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertbutton)
                    .addComponent(updatebutton)
                    .addComponent(deletebutton)
                    .addComponent(displaybutton))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbutton)
                    .addComponent(exitbutton))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        statisticspane.addTab("Drivers", jPanel1);

        jLabel5.setText("Team No");

        jLabel6.setText("Team");

        jLabel7.setText("Engine");

        jLabel8.setText("Base Of Operations");

        jLabel9.setText("Driver1");

        jLabel10.setText("Driver2");

        jLabel11.setText("Principal");

        teams_insert.setText("Insert");

        teams_update.setText("Update");

        teams_delete.setText("Delete");

        teams_display.setText("Display");

        teams_clear.setText("Clear");

        teams_exit.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teams_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teams_exit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teams_insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teams_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teams_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teams_display))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(team_no, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(engine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(base_op, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driver1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driver2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(713, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(team_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(engine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(base_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(driver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(driver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teams_insert)
                    .addComponent(teams_update)
                    .addComponent(teams_delete)
                    .addComponent(teams_display))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teams_clear)
                    .addComponent(teams_exit))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        statisticspane.addTab("Teams", jPanel2);

        jLabel12.setText("Race ID");

        jLabel13.setText("GP Name");

        jLabel14.setText("Circuit");

        jLabel15.setText("Location");

        jLabel16.setText("Date");

        jLabel17.setText("Laps");

        jLabel18.setText("Lap Length");

        jLabel19.setText("Winning Driver");

        jLabel20.setText("Winning Team");

        gps_ins.setText("Insert");

        gps_upd.setText("Update");

        gps_del.setText("Delete");

        gps_disp.setText("Display");

        gps_clear.setText("Clear");

        gps_exit.setText("Exit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gps_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gps_exit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gps_ins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gps_upd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gps_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gps_disp))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gpname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(winning_team, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(winning_driver, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lap_length)
                                .addComponent(raceid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(circuit, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_of_race, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(no_of_laps, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(raceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(circuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_of_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no_of_laps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lap_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(winning_driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(winning_team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gps_ins)
                    .addComponent(gps_upd)
                    .addComponent(gps_del)
                    .addComponent(gps_disp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gps_clear)
                    .addComponent(gps_exit))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        statisticspane.addTab("GPs", jPanel3);

        jLabel21.setText("Drivers Standings");

        drivstandings.setColumns(20);
        drivstandings.setRows(5);
        jScrollPane1.setViewportView(drivstandings);

        jLabel22.setText("Teams Standings");

        teamstandings.setColumns(20);
        teamstandings.setRows(5);
        jScrollPane2.setViewportView(teamstandings);

        drivchampbutton.setText("Find Drivers Champion(s)");
        drivchampbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivchampbuttonActionPerformed(evt);
            }
        });

        drivchamp.setColumns(20);
        drivchamp.setRows(5);
        jScrollPane3.setViewportView(drivchamp);

        teamchampbutton.setText("Find Teams Champion(s)");
        teamchampbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamchampbuttonActionPerformed(evt);
            }
        });

        teamchamp.setColumns(20);
        teamchamp.setRows(5);
        jScrollPane4.setViewportView(teamchamp);

        jLabel23.setText("Enter GP Name");

        jLabel24.setText("Date");

        jLabel25.setText("Winning Driver");

        jLabel26.setText("Winning Team");

        jLabel27.setText("Enter Driver Name");

        drivraceswon.setColumns(20);
        drivraceswon.setRows(5);
        jScrollPane5.setViewportView(drivraceswon);

        jLabel28.setText("Races Won");

        findracedrivwon.setText("Find Races Won");
        findracedrivwon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findracedrivwonActionPerformed(evt);
            }
        });

        statfinddetails.setText("Find Details");
        statfinddetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statfinddetailsActionPerformed(evt);
            }
        });

        jLabel30.setText("Enter Team Name");

        jLabel31.setText("Races Won");

        statraceswonteam.setColumns(20);
        statraceswonteam.setRows(5);
        jScrollPane6.setViewportView(statraceswonteam);

        teamraceswon.setText("Find Races Won");
        teamraceswon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamraceswonActionPerformed(evt);
            }
        });

        clearstat.setText("Clear All");
        clearstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearstatActionPerformed(evt);
            }
        });

        exitstat.setText("Exit");
        exitstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitstatActionPerformed(evt);
            }
        });

        standingsdisp.setText("Display Standings");
        standingsdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsdispActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(clearstat)
                        .addGap(29, 29, 29)
                        .addComponent(exitstat)
                        .addGap(18, 18, 18)
                        .addComponent(standingsdisp)))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(drivchampbutton)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(teamchampbutton)
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findracedrivwon)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(drivname)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(statfinddetails)
                        .addComponent(gpnamestat)
                        .addComponent(gpdatestat)
                        .addComponent(gpwinningdriver)
                        .addComponent(gpwinningteam)
                        .addComponent(stateamname, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addComponent(teamraceswon))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(drivchampbutton))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teamchampbutton))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel27))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(drivname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stateamname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel30))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel29)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(findracedrivwon)
                                    .addComponent(teamraceswon)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clearstat)
                                    .addComponent(exitstat)
                                    .addComponent(standingsdisp))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(gpnamestat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gpdatestat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gpwinningdriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gpwinningteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statfinddetails)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        statisticspane.addTab("Statistics", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticspane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticspane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void standingsdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsdispActionPerformed
        try
        {
            cstmt=con.prepareCall("begin driverstandings(?); end;");
            cstmt.registerOutParameter(1, Types.VARCHAR);
            cstmt.execute();
            String str4=cstmt.getString(1);
            str4=str4.replaceAll("&&","\n");
            drivstandings.setText(str4);
            cstmt=con.prepareCall("begin teamstandings(?); end;");
            cstmt.registerOutParameter(1, Types.VARCHAR);
            cstmt.execute();
            String str3=cstmt.getString(1);
            str3=str3.replaceAll("&&","\n");
            teamstandings.setText(str3);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_standingsdispActionPerformed

    private void clearstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearstatActionPerformed
       drivstandings.setText(null);
       teamstandings.setText(null);
       drivchamp.setText(null);
       teamchamp.setText(null);
       drivname.setText(null);
       drivraceswon.setText(null);
       gpnamestat.setText(null);
       gpdatestat.setText(null);
       gpwinningdriver.setText(null);
       gpwinningteam.setText(null);
       stateamname.setText(null);
       statraceswonteam.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_clearstatActionPerformed

    private void exitstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitstatActionPerformed
        System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_exitstatActionPerformed

    private void findracedrivwonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findracedrivwonActionPerformed
 try
        {
            
            stmt=con.createStatement();
            rs=stmt.executeQuery("select g.gpname from  gps g INNER JOIN drivers d ON (g.winning_driver=d.driver_no)  where d.name='"+drivname.getText()+"'");       // TODO add your handling code here:
            String racesWon = "";
            int i=0;
            while(rs.next())
            {
                
                i++;
                if(i==1)
                {
                    racesWon = rs.getString(1);
                }
                else
                {
                    racesWon = racesWon.concat("\n").concat(rs.getString(1));
                }
                drivraceswon.setText(racesWon);
            }
            JOptionPane.showMessageDialog(this, "The races won by the particular driver are displayed!!");
          
        }
  catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_findracedrivwonActionPerformed

    private void drivchampbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivchampbuttonActionPerformed
     try
        {
            cstmt=con.prepareCall("begin championdriv(?); end;");
            cstmt.registerOutParameter(1, Types.VARCHAR);
            cstmt.execute();
            String str4=cstmt.getString(1);
            str4=str4.replaceAll("&&","\n");
            drivchamp.setText(str4);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }        
    }//GEN-LAST:event_drivchampbuttonActionPerformed

     
    private void statfinddetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statfinddetailsActionPerformed
       try
        {
            
            stmt=con.createStatement();
            rs=stmt.executeQuery("select g.date_of_race,d.name,t.team from gps g JOIN drivers d ON (d.driver_no=g.winning_driver) JOIN teams t ON (t.team_no=g.winning_team) where gpname='"+gpnamestat.getText()+"'");       // TODO add your handling code here:
            rs.next();
            gpdatestat.setText(rs.getString(1));
            gpwinningdriver.setText(rs.getString(2));
            gpwinningteam.setText(rs.getString(3));
        }
  catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(this, ex.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_statfinddetailsActionPerformed

    private void teamchampbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamchampbuttonActionPerformed
       try
        {
            cstmt=con.prepareCall("begin championteam(?); end;");
            cstmt.registerOutParameter(1, Types.VARCHAR);
            cstmt.execute();
            String str4=cstmt.getString(1);
            str4=str4.replaceAll("&&","\n");
            teamchamp.setText(str4);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_teamchampbuttonActionPerformed

    private void teamraceswonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamraceswonActionPerformed
        try
        {
            
            stmt=con.createStatement();
            rs=stmt.executeQuery("select g.gpname from  gps g INNER JOIN teams t ON (g.winning_team=t.team_no)  where t.team='"+stateamname.getText()+"'");       // TODO add your handling code here:
            String racesWon = "";
            int i=0;
            while(rs.next())
            {
                
                i++;
                if(i==1)
                {
                    racesWon = rs.getString(1);
                }
                else
                {
                    racesWon = racesWon.concat("\n").concat(rs.getString(1));
                }
                statraceswonteam.setText(racesWon);
            }
            JOptionPane.showMessageDialog(this, "The races won by the particular team are displayed!!");
          
        }
  catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(this, ex.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_teamraceswonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new f1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField base_op;
    private javax.swing.JTextField circuit;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton clearstat;
    private javax.swing.JTextField date_of_race;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton displaybutton;
    private javax.swing.JTextArea drivchamp;
    private javax.swing.JButton drivchampbutton;
    private javax.swing.JTextField driver1;
    private javax.swing.JTextField driver2;
    private javax.swing.JTextField driver_no;
    private javax.swing.JTextField drivname;
    private javax.swing.JTextArea drivraceswon;
    private javax.swing.JTextArea drivstandings;
    private javax.swing.JTextField engine;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton exitstat;
    private javax.swing.JButton findracedrivwon;
    private javax.swing.JTextField gpdatestat;
    private javax.swing.JTextField gpname;
    private javax.swing.JTextField gpnamestat;
    private javax.swing.JButton gps_clear;
    private javax.swing.JButton gps_del;
    private javax.swing.JButton gps_disp;
    private javax.swing.JButton gps_exit;
    private javax.swing.JButton gps_ins;
    private javax.swing.JButton gps_upd;
    private javax.swing.JTextField gpwinningdriver;
    private javax.swing.JTextField gpwinningteam;
    private javax.swing.JTextField gpwins;
    private javax.swing.JButton insertbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField lap_length;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField no_of_laps;
    private javax.swing.JTextField principal;
    private javax.swing.JTextField raceid;
    private javax.swing.JButton standingsdisp;
    private javax.swing.JTextField stateamname;
    private javax.swing.JButton statfinddetails;
    private javax.swing.JTabbedPane statisticspane;
    private javax.swing.JTextArea statraceswonteam;
    private javax.swing.JTextField team;
    private javax.swing.JTextField team_no;
    private javax.swing.JTextArea teamchamp;
    private javax.swing.JButton teamchampbutton;
    private javax.swing.JButton teamraceswon;
    private javax.swing.JButton teams_clear;
    private javax.swing.JButton teams_delete;
    private javax.swing.JButton teams_display;
    private javax.swing.JButton teams_exit;
    private javax.swing.JButton teams_insert;
    private javax.swing.JButton teams_update;
    private javax.swing.JTextArea teamstandings;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField winning_driver;
    private javax.swing.JTextField winning_team;
    // End of variables declaration//GEN-END:variables
}
